### ISSUE TITLE
Details/summary elements may be broken on Edge

### ISSUE THREAD

**Issue by pcraig3** [cds-snc/c19-benefits-node#14]
## Summary

We noticed a couple problems with rendering details/summary elements, as well as svgs in Edge. It looks like you don't have them at the moment, but if you start adding them, ping me and I'll test them out in browserstack.

More detail can be found here: https://github.com/cds-snc/cra-claim-tax-benefits/pull/417

**Comment by dsamojlenko** [comment]
Closing for now, will address if the need arises
