### ISSUE TITLE
Focus indicator issue

### ISSUE THREAD

**Issue by dsamojlenko** [cds-snc/c19-benefits-node#215]
When you tab to, and activate a link that takes you elsewhere on the same page (ex: “Skip to main content”), when your focus lands on the target element, the visual focus indicator disappears until you hit tab again.

**Comment by CalvinRodo** [comment]
This is done using Javascript in WxT. Do we want to replicate that here?

**Comment by CalvinRodo** [comment]
Looking at the success criteria for 2.4.7 

https://www.w3.org/WAI/WCAG21/Understanding/focus-visible.html

It looks like since we aren't linking to a keyboard operable item then we don't need to highlight, reaching out to WS CoE to confirm.

**Comment by dsamojlenko** [comment]
Closing as not going to implement for now.
