### ISSUE TITLE
Log Exceptions as a structured json object to std out .

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/c19-benefits-node#250]

**Comment by dsamojlenko** [comment]
I believe they are?

**Comment by CalvinRodo** [comment]
okay I'll change this to "Log a structured error message to std out"

**Comment by pcraig3** [comment]
Hey @CalvinRodo, I did this on CRA already. Did you want to chat about it?

**Comment by pcraig3** [comment]
Check out the PR description: https://github.com/cds-snc/cra-claim-tax-benefits/pull/254

**Comment by CalvinRodo** [comment]
Cool I'll check that out.

**Comment by CalvinRodo** [comment]
Partially done in PR #274 
Exceptions are now being logged in middleware
