### ISSUE TITLE
Error pages design/content

### ISSUE THREAD

**Issue by dsamojlenko** [cds-snc/c19-benefits-node#297]
Our error pages could use a bit of content/design love.

[Trello backlog ticket](https://trello.com/c/HakcnXr6/102-error-screen-content-design)

## Current error pages

500 Server Error | 404 Not Found Error
---------------- | ---------------
![image](https://user-images.githubusercontent.com/1187115/80394860-7185b180-8880-11ea-93e1-1d7b301dd547.png) | ![image](https://user-images.githubusercontent.com/1187115/80394930-85311800-8880-11ea-897c-6dc4c5dea86c.png)

Here is an example of a 404 Not Found error page on Canada.ca:

![image](https://user-images.githubusercontent.com/1187115/80395094-bf021e80-8880-11ea-8771-c0e7c5fabfa4.png)

...I wasn't able to trigger a 500 error on Canada.ca, so not sure what they look like, but here's the sample included with WxT:

![image](https://user-images.githubusercontent.com/1187115/80395332-07b9d780-8881-11ea-92d3-caa06ab18f21.png)

**Comment by CalvinRodo** [comment]
Completed with #324
