### ISSUE TITLE
Alpha 7 - CESB Student Benefit related changes

### ISSUE THREAD

**Issue by dsamojlenko** [cds-snc/c19-benefits-node#308]
This ticket covers the Student Benefit related changes in Alpha 7. These changes should be held in draft until Content and Design reviews, and fact checking occurs.

This ticket includes:
- New Benefits cards
- M9 Question
- M2c new option
- M2a new option
- Benefit calculation updates
- Routing changes

As soon as changes from issue #307 are completed and merged, they should be merged with this work

**Comment by katedee** [comment]
If we want to break this out further, someone can take on the benefit cards and calculation updates, while I get on the question, new options + routing
