### ISSUE TITLE
Updates to CERB card 

### ISSUE THREAD

**Issue by sidewalkballet** [cds-snc/c19-benefits-node#341]
Last one hopefully promise 

EN: https://www.figma.com/file/HTlKvyFVKgzH458fWFRtza/Benefits-Finder-and-Calculator?node-id=2600%3A6069

![image](https://user-images.githubusercontent.com/3474250/80837368-a7020600-8bc4-11ea-939e-9188af52b003.png)

FR: https://www.figma.com/file/HTlKvyFVKgzH458fWFRtza/Benefits-Finder-and-Calculator?node-id=2835%3A5951

![image](https://user-images.githubusercontent.com/3474250/80837653-3d362c00-8bc5-11ea-88d6-fe44c82d08db.png)

**Comment by katedee** [comment]
Resolved in #357
