### ISSUE TITLE
Translate results query string. 

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/c19-benefits-node#366]
To comply with the spirit of the Directive on Official Languages for Communications and Services we should translate our query strings on the results page when the language switches. 

At the moment we do comply with the directive since it only mentions the Domain. 

https://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=26164#sec6.6

**Comment by dsamojlenko** [comment]
yeah, this will not be an easy lift, I am pretty sure querystrings aren't covered under this. If they are, then I'd suggest doing without the bookmarking feature.
