### ISSUE TITLE
add high school graduates for CESB

### ISSUE THREAD

**Issue by katewilhelm** [cds-snc/c19-benefits-node#422]
add option under "Income the same" - screen M2c in figma
result mapping updated in Calvin's spreadsheet under May 8 tab https://docs.google.com/spreadsheets/d/11DSoj5_NDiznVITuSDcedxfNSMSGTwTm9B0J1Jwv1Ww/edit#gid=663536631 

check that high school graduates are included in CESB benefit card in the first bullet - Previously missing from French translation

i believe we are still holding this in staging

**Comment by sidewalkballet** [comment]
Noting change to M2c as outlined in this issue: https://github.com/cds-snc/c19-benefits-node/issues/433
