### ISSUE TITLE
Feedback not coming through on Airtable 

### ISSUE THREAD

**Issue by sidewalkballet** [cds-snc/c19-benefits-node#425]
We received a fairly steady stream of feedback this morning, but it stopped around noon. 

1. go leave some feedback https://covid-benefits.alpha.canada.ca/en/lost-job
2. go to airtable https://airtable.com/tbl8OJIDF5vv6jvdc/viwbrA88ofIQJ3rZ6

Observe the feedback is not there. Expected that the feedback would be there.

**Comment by CalvinRodo** [comment]
Issue was a column got renamed in airtable which broke the integration.
