### ISSUE TITLE
Copy additions to start page

### ISSUE THREAD

**Issue by katedee** [cds-snc/c19-benefits-node#431]
A bit of content was added to the start (m0) page

**Comment by sidewalkballet** [comment]
EN: https://www.figma.com/file/HTlKvyFVKgzH458fWFRtza/Benefits-Finder-and-Calculator?node-id=3382%3A1

FR: https://www.figma.com/file/HTlKvyFVKgzH458fWFRtza/Benefits-Finder-and-Calculator?node-id=3382%3A68

**Comment by sidewalkballet** [comment]
OBE; we can add OAS and CESB now.
