### ISSUE TITLE
Typos on the FR start page

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/c19-benefits-node#447]
vorte -> votre
Êtes vous -> Êtes-vous

AirTable URL: https://airtable.com/tbl8OJIDF5vv6jvdc/viwbrA88ofIQJ3rZ6/rechVBG7yC9cXwoCt

**Comment by katedee** [comment]
This was solved even before the bug was logged. Recommend double checking for the future :)
https://github.com/cds-snc/c19-benefits-node/issues/447
